### ISSUE TITLE
Contribute to Open Source: Beginner-Friendly DSA Questions

### ISSUE THREAD

**Issue by Arijeet2580** [Arijeet2580/HacktoberfestCode2023#12]
## Merge Sort Implementation

**Description**: Implement the Merge Sort algorithm in your preferred programming language. Ensure that it can sort an array of integers in ascending order. You should provide both **the** iterative and recursive versions of the algorithm.

```terminal
arr = [38, 27, 43, 3, 9, 82, 10]
```
OUTPUT: 
```terminal
sorted_arr = [3, 9, 10, 27, 38, 43, 82]
```

## Find the Longest Increasing Subsequence

Description: Write a function that finds and returns the length of the longest increasing subsequence in an array of integers. An increasing subsequence is a set of elements where each element is larger than the previous one but not necessarily consecutive.

```terminal
arr = [10, 22, 9, 33, 21, 50, 41, 60, 80]

```
- The longest increasing subsequence is [10, 22, 33, 50, 60, 80], with a length of 6.

**Comment by parmesh-bhatt** [comment]
Hi, @Arijeet2580, I am Parmesh B.
I hope you are fine.
Can you assign this issue to me?
